name: inference-comm
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - matplotlib
  - tensorflow-gpu
  - cudatoolkit=10.1
  - cudnn
  - requests
  - pandas
  - psutil
  - pip:
    - gym
    - ray[rllib]
    - gputil